name: Compiling

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        compiler: [gcc, clang, cl]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up compiler
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          choco install mingw -y
        elif [ "${{ matrix.compiler }}" == "gcc" ]; then
          sudo apt-get install -y g++
        elif [ "${{ matrix.compiler }}" == "clang" ]; then
          sudo apt-get install -y clang
        fi

    - name: Build
      run: ./configure --build=debug
